apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "timed.fullname" . }}-frontend
  labels:
    {{- include "timed.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  TIMED_SSO_CLIENT_HOST: {{ .Values.auth.oidc.url | quote }}
  TIMED_SSO_CLIENT_ID: {{ .Values.auth.oidc.client.id | quote }}
