{{- if .Values.postgresql.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgresql-ingress
  labels:
    {{- include "timed.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: tcp-postgresql
  selector:
{{ toYaml .Values.postgresql.ingress.selector | indent 4 }}
  {{- if .Values.postgresql.ingress.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{ .Values.postgresql.ingress.loadBalancerSourceRanges | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
