ingress:
  enabled: true
  hostname: <hostname>

  annotations:
    "kubernetes.io/ingress.class": nginx
    "cert-manager.io/issuer": sentry-issuer
    "nginx.ingress.kubernetes.io/proxy-body-size": "200m"
    "nginx.ingress.kubernetes.io/enable-cors": "true"
    "nginx.ingress.kubernetes.io/cors-allow-methods": "PUT,GET,POST,OPTIONS"
    "nginx.ingress.kubernetes.io/cors-allow-origin": "*"
    "nginx.ingress.kubernetes.io/cors-allow-credentials": "true"


  tls:
    - hosts:
        - <hostname>
      secretName: sentry-tls

postgresl:
  postgresqlPassword: change-me

system:
  secretKey: chamge-me
