apiVersion: v2
name: back8sup
description: Deploy back8sup to a Kubernetes Cluster
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: latest
home: https://github.com/adfinis-sygroup/back8sup
sources:
  - https://github.com/adfinis-sygroup/back8sup
  - https://github.com/adfinis-sygroup/helm-charts/tree/master/charts/back8sup
maintainers:
  - name: adfinis-sygroup
    email: support@adfinis.com
    url: https://adfinis.com
