{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "osschallenge.fullname" . }}
  labels:
    {{- include "osschallenge.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            rmd:
              serviceName: {{ $.Values.osschallenge.service.name }}
              servicePort: {{ $.Values.osschallenge.service.externalPort }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
    {{ toYaml .Values.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end -}}
