apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.osschallenge.service.name }}
  labels:
    {{- include "osschallenge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.osschallenge.service.type }}
  ports:
    - port: {{ .Values.osschallenge.service.externalPort }}
      targetPort: {{ .Values.osschallenge.service.internalPort }}
      protocol: TCP
      name: {{ .Values.osschallenge.service.name }}
  selector:
    {{- include "osschallenge.selectorLabels" . | nindent 4 }}
