name: Lint and Test Charts

on:
  pull_request:
  push:
    branches:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v1

    - name: Setup environment for pre-commit
      run: hack/ci/github/setup/pre-commit.sh

    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - uses: pre-commit/action@v1.0.1

  lint-test:
    name: Lint and Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: hack/chart-testing/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-rc.1
        if: steps.lint.outputs.changed == 'true'

      - name: Setup cluster for chart-testing (install)
        run: hack/deploy/init.sh
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install
          config: hack/chart-testing/ct-install.yaml
